# Generated by Django 5.2 on 2025-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faultthreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultthreshold',
            name='datapoint',
        ),
        migrations.RemoveField(
            model_name='faultthreshold',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='faultthreshold',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='faultthreshold',
            name='min_value',
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='humidity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='humidity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='occupancy_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='power_kw_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='power_kw_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='sensitivity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='sensitivity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='sensor_online_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultthreshold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
