# Generated by Django 5.2 on 2025-04-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_faultthreshold_datapoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='code',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotels',
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_identifier', models.TextField(blank=True, null=True)),
                ('sensor_type', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='FaultStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fault_type', models.TextField()),
                ('status', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_statuses', to='api.device')),
            ],
            options={
                'db_table': 'fault_status',
            },
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='IoTDevice',
        ),
    ]
