# Generated by Django 5.2 on 2025-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_iotdevice_room_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faultstatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faultthreshold',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faultstatus',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='floor',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='faultthreshold',
            table='fault_thresholds',
        ),
        migrations.AlterModelTable(
            name='floor',
            table='floors',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
