# Generated by Django 5.2 on 2025-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_device_options_alter_faultstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='hotel',
            new_name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='faultstatus',
            name='device',
        ),
        migrations.AddField(
            model_name='faultstatus',
            name='device_id',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
