# Generated by Django 5.2 on 2025-04-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_hotel_floor_hotel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.floor'),
            preserve_default=False,
        ),
    ]
